#!/bin/bash

# Add here any the actions which are required before plugin build
# like packages building, packages downloading from mirrors and so on.
# The script should return 0 if there were no errors.
set -x
PLUGIN_DIR=$(cd `dirname $0` && pwd -P)

# do some preflight checks on some of the required utilities to build this
# plugin.
CMDS="librarian-puppet dh_make"
for CMD in $CMDS; do
  command -v $CMD >/dev/null && continue || { echo "${CMD} not installed"; exit 1; }
done

# don't package the .git folders for the plugins we download
pushd ${PLUGIN_DIR}/deployment_scripts/puppet
librarian-puppet install --path=./modules
for DIR in `find ${PLUGIN_DIR}/deployment_scripts/puppet -iname '.git'`; do
  rm -rf "${DIR}"
done
popd

#
# comment out this section if you don't wish to build the packages at plugin
# build time
#
pushd ${PLUGIN_DIR}/repositories/ubuntu/
${PLUGIN_DIR}/.utils/build_all_debs.sh
popd
